WebAppProject/urls.py
from django.conf.urls import url
from WebAppProject import views


# list of urls defined for our website
# making use of django namespacing
app_name = 'workoutweb'
urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^about/', views.about, name='about'),
    url(r'^account/', views.account, name='account'),
    url(r'^account_settings/', views.account_settings, name='account_settings'),
    url(r'^nearest_gym/', views.nearestgym, name='nearest_gym'),
    url(r'^contact/', views.contact, name='contact'),
    url(r'^faq/', views.faq, name='faq'),
    url(r'^restricted/', views.restricted, name='restricted'),
    url(r'^category/(?P<category_name_slug>[\w\-]+)/$',
        views.show_category, name='show_category'),
    url(r'^category/(?P<category_name_slug>[\w\-]+)/(?P<post_name_slug>[\w\-]+)/$',
        views.show_post, name='show_post'),
    url(r'^category/(?P<category_name_slug>[\w\-]+)/(?P<post_name_slug>[\w\-]+)/liked/$',
        views.liked, name='liked'),
    url(r'^category/(?P<category_name_slug>[\w\-]+)/(?P<post_name_slug>[\w\-]+)/disliked/$',
        views.disliked, name='disliked'),
    url(r'^category/(?P<category_name_slug>[\w\-]+)/(?P<post_name_slug>[\w\-]+)/removepost/$',
        views.removepost, name='Remove Post'),
    url(r'', views.index, name='index'),
]

workoutweb/urls.py
from django.conf.urls import url
from django.contrib import admin
from WebAppProject import views
from django.conf.urls import include
from django.conf import settings
from django.conf.urls.static import static
from registration.backends.simple.views import RegistrationView

class MyRegistrationView(RegistrationView):
    def get_success_url(self,user):
        return '/workoutweb/'

urlpatterns = [
    url(r'^$', views.index, name ='index'),
    url(r'^workoutweb/', include('WebAppProject.urls')),
    url(r'^admin/', admin.site.urls),
    url(r'^accounts/register/$',
        views.register, name='Register'),
    url(r'^accounts/logout/$',
        views.user_logout, name='Logout'),
    url(r'^accounts/login/$',
        views.user_login, name='Login'),
    url(r'^accounts/', include('registration.backends.simple.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

templates/workoutweb/about.html
{% extends 'workoutweb/base.html' %}
{% load staticfiles %}

{%  block body_block %}
    <!-- Page Content -->
    <div class="container">

        <!-- Introduction Row -->
        <div class="row">
            <div class="col-lg-12">
                <h1 class="page-header">About Us
                    <small>It's Nice to Meet You!</small>
                </h1>
                <p>We are the creators of WorkoutWeb! A forum that revolves around
                    all things fitness and workout, WorkoutWeb is targeted towards
                    anyone interested in sharing their hints, tips and progress.</br>
                    As well as, those who are wanting to improve their fitness or
                    lose weight.The aim of WorkoutWeb is to provide a place for
                    anyone to access information on other users’ inspiration and
                    workout styles, simply a place for users to show off how much they
                    can deadlift or for users to just ask questions or follow fitness threads.</br>
                    Our team is made up of 4 members all studying Computer Science at
                    the university of glasgow.
                </p>
            </div>
        </div>

        <!-- Team Members Row -->
        <div class="row">
            <div class="col-lg-12">
                <h2 class="page-header">Our Team</h2>
            </div>

            <div class="col-lg-4 col-sm-6 text-center">
                <img class="img-circle img-center" src="{% static "images/abdul.jpg" %}"
                    alt="Abdul" width="300" height="300"/>
                <h3>Abdul
                    <small>Back-End WebApp Dev</small>
                </h3>
            </div>

            <div class="col-lg-4 col-sm-6 text-center">
                <img class="img-circle img-center" src="{% static "images/jaskaran.jpg" %}"
                    alt="Jaskaran" width="300" height="300"/>
                <h3>Jaskaran
                    <small>Back-End WebApp Dev</small>
                </h3>
            </div>

            <div class="col-lg-4 col-sm-6 text-center">
                <img class="img-circle img-center" src="{% static "images/millie.jpg" %}"
                    alt="Millie" width="300" height="300">
                <h3>Millie
                    <small>Junior WebApp Dev</small>
                </h3>
            </div>

            <div class="col-lg-4 col-sm-6 text-center">
                <img class="img-circle img-center" src="{% static "images/naji.jpg" %}"
                    alt="Naji" width="300" height="300"/>
                <h3>Naji
                    <small>CSS KING</small>
                </h3>
            </div>
        </div>
    </div>

{% endblock %}

templates/workoutweb/account.html
{%  extends 'workoutweb/base.html' %}
{% load staticfiles %}


{% block title_block %}
    My Account Page
{% endblock %}

{% block body_block %}

    <!-- User's profile picture and default background picture -->
    <div class = "profilepic">
        {% if user.userprofile.picture %}
            <img class="img-circle img-center" src="{{ MEDIA_URL }}{{ user.userprofile.picture}}"
                alt="profilepic" width="300" height="300"/>
        {% else %}
            <img class="img-circle img-center" src="{% static 'images/default-profile.jpg' %}"
                alt="profilepic" width="300" height="300"/>
        {% endif %}
    </div>

    <div class="container">

        <!-- Introduction Row -->
        <div class="row">
            <div class="col-lg-12">
                <h1 class="page-header">Username: {{ user.userprofile.user }}</h1>
                <strong>Bio:</strong> <p>{{user.userprofile.bio }}<br></p>
            </div>
            <div class="col-sm-2">
                <div>
                    <strong>Details:</strong>
                    <div class="row">
                        <div class="container">
                            {% if user.userprofile.weight %}
                                <p>Weight: {{ user.userprofile.weight }}kg</p>
                            {% else %}
                                <p>Weight: N/A</p>
                            {% endif %}
                            {% if user.userprofile.height %}
                                <p>Height: {{ user.userprofile.height }}cm</p>
                            {% else %}
                                <p>Height: N/A</p>
                            {% endif %}
                        </div>
                    </div>
                </div>
            </div>
        </div>

        <strong>click here to update your profile page</strong>
        <a href="{% url 'workoutweb:account_settings' %}">Account Settings</a></br>
        <hr>
    </div>

    <!-- Row 2 for list of liked posts and posts created; split into 2 columns -->
    <div class="row">

        <div class="col-sm-6">
            <div class="well">
                <h4>Posts you liked:</h4>
                <div class="row">
                    <div class="container">
                        {% if post %}
                            {% for userpost in post %}
                                <ul>
                                    <li><strong><a href="{% url 'workoutweb:show_post' userpost.category.slug userpost.slug %}">{{ userpost.title }}</a></strong></li>
                                </ul>
                            {% endfor %}
                        {% else %}
                            <p>No posts to show</p>
                        {% endif %}
                    </div>
                </div>
            </div>
        </div>

        <div class="col-sm-6">
            <div class="well">
                <h4>Your Posts:</h4>
                <div class="row">
                    <div class="container">
                        {% if userspost %}
                            {% for userpost in userspost %}
                                <ul>
                                    <li><strong><a href="{% url 'workoutweb:show_post' userpost.category.slug userpost.slug %}">{{ userpost.title }}</strong></li>
                                </ul>
                            {% endfor %}
                        {% else %}
                            <p>No posts to show</p>
                        {% endif %}
                    </div>
                </div>
            </div>
        </div>
    </div>



{% endblock %}

templates/workoutweb/account_settings.html
{%  extends 'workoutweb/base.html' %}
{%  block body_block %}
    <h2>Account Settings</h2>

    <!-- Account Settings form -->
    <form id="accounts_form" method="post" action="."
                  enctype="multipart/form-data">

        {% csrf_token %}

        <div class="form-group">
          <label for="bio">BIO:</label>
          <input type="text" class="form-control" id="bio" placeholder="Enter bio: " name="bio" value="" size="50"  >
        </div>
        <div class="form-group">
          <label for="weight">Weight:</label>
          <input type="number" class="form-control" id="weight" placeholder="Enter Weight: in Kg's " name="weight"min="0">
        </div>
        <div class="form-group">
          <label for="height">Height:</label>
          <input type="number" class="form-control" id="height" placeholder="Enter Height: in meters" name="height"min="0">
        </div>
          <div class="form-group">
          <label for="picture">Picture:</label>
          <input type="file" class="form-control" id="picture" placeholder="Upload picture" name="Picture">
          </div>
        <button type="submit" class="btn btn-default">Update Profile</button>
    </form>

    {% if updated %}
        <strong>You have successfully updated your profile!</strong>
        <a href="{% url 'workoutweb:account' %}">click to go back to your account.</a><br />
    {% endif %}
{% endblock %}

templates/workoutweb/base.html
<!DOCTYPE html>
{% load workoutweb_template_tags %}
{%  load staticfiles %}

<html>
<head>
    <meta charset="utf-8">
    <title>WorkoutWeb</title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" type="text/css" href="{% static 'styles.css' %}"  media="screen" />
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.1.1/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
    <script src="http://code.jquery.com/jquery-1.10.1.min.js"></script>


</head>
<body>

    <!-- Navbar -->
    <nav class="navbar navbar-inverse">
        <div class="container-fluid">
            <div class="navbar-header">
                <a class="navbar-brand" href="/workoutweb/"> WorkoutWeb</a>
            </div>
            <ul class="nav navbar-nav">
                <li class="dropdown"><a class="dropdown-toggle" data-toggle="dropdown" href="">Categories <span class="caret"></span></a>
                    <ul class="dropdown-menu">
                        {% get_category_list %}
                    </ul>
                <li><a href="{% url 'workoutweb:nearest_gym' %}">Find Nearest Gym</a></li>
                <li><a href="{% url 'workoutweb:about' %}">About Us</a></li>
                <li><a href="{% url 'workoutweb:contact' %}">Contact Us</a></li>
                <li><a href="{% url 'workoutweb:faq' %}">FAQ</a></li>
            </ul>
            <ul class="nav navbar-nav navbar-right">
                {% if user.is_authenticated %}
                    <li><a href="{% url 'workoutweb:account' %}">My Account</a></li>
                    <li><a href="/accounts/logout/"><span class="glyphicon glyphicon-log-out"></span> Logout</a></li>

                {% else %}
                    <li><a href="/accounts/register"><span class="glyphicon glyphicon-user"></span> Sign Up</a></li>
                    <li><a href="/accounts/login"><span class="glyphicon glyphicon-log-in"></span> Login</a></li>
                {% endif %}
            </ul>
        </div>
    </nav>

    <!-- BobdyBlock -->
    <div>
        {% block body_block %}
        {% endblock %}
    </div>

    <!-- Footer -->
    <footer>
        <div class="row">
            <div>
                <p>Copyright &copy; WorkoutWeb 2017</p>
            </div>
        </div>
    </footer>

</body>

templates/workoutweb/category.html
{% extends 'workoutweb/base.html' %}

{% block title_block %}
    Categories
{% endblock %}


{% block body_block %}
    <!-- Page Content -->
    <div class="container">

        <div class="row">

            <!-- Blog Entries Column -->
            <div class="col-md-10">

                <h1 class="page-header">
                    {% if category %}
                        {{ category.name }}
                        <small>Posts:</small>
                        </h1>

                        <!-- Posts -->
                        {% if posts %}
                             {% for post in posts %}
                                <h2><b><a href="{% url 'workoutweb:show_post' category.slug post.slug %}">{{ post.title }}</a></b></h2>

                                <!-- Date/Time Likes/Views-->
                                <p><span class="glyphicon glyphicon-time"></span> {{ post.time }}</p>

                                <!-- Post Content -->
                                <div class="lead">
                                    <p>{{ post.content }} </p>
                                </div>
                                <p><span class="glyphicon glyphicon-thumbs-up"</span><b>likes:</b>{{post.likes}} <span class="glyphicon glyphicon-eye-open"</span><b>views:</b>{{post.views}}</p>

                                <br>
                                {% if post in usercreatedposts %}
                                    <form action="/workoutweb/category/{{ category.slug }}/{{ post.slug }}/removepost/" method="delete">
                                        {% csrf_token %}
                                        <button type="submit" value="preview" name="Preview">Delete post</button>
                                    </form>
                                {% endif %}

                                <hr>
                             {% endfor %}
                        {% else %}
                             <strong>No posts currently in category.</strong>
                        {% endif %}

                        <!-- Checks if a post is same title -->
                        {% if repeat %}
                            <b><font size="3" color="red">{{ repeat }}</font></b>
                        {% endif %}
                        <!--Creating a new post-->
                        {% if user.is_authenticated %}
                        <h3>Post information</h3>
                        <form id="post_form" method="post" action="/workoutweb/category/{{ category.slug }}/">
                            <div>
                                {% csrf_token %}
                                <div class="form-group">
                                    <label for="title">Title:</label>
                                    <input type="text" class="form-control" form="post_form" id="title" placeholder="Enter title" name="title" value="" size="50" required>
                                    <textarea class="form-control" form="post_form" rows="3" name="content" value="Post content" required></textarea>
                                </div>

                                <button type="submit" class="btn btn-primary">Submit</button>
                            </div>
                        </form>
                        {% else %}
                          <b> <font size="5" color="Black"> In order to create a post, please <a href="/accounts/register/">sign up</a> for an account.</font></b>
                        {% endif %}
                    {% else %}
                        The specified category does not exist!
                    {% endif %}
            </div>
        </div>
    </div>
{%  endblock %}

templates/workoutweb/cats.html
<!-- Loop through categories in category -->
{% if cats %}
<ul>
    {% for c in cats %}
        <li ><a href="{% url 'workoutweb:show_category' c.slug %}">{{ c.name }}</a></li>
    {% endfor %}
{% else %}
    <li> <strong>There are no categories present.</strong></li>
{% endif %}
</ul>

templates/workoutweb/contact.html
{% extends 'workoutweb/base.html' %}
{% load staticfiles %}

{% block title_block %}
    Contact Us
{% endblock %}

{% block body_block %}

    <div class="container">

        <!-- Introduction Row -->
        <div class="row">
            <div class="col-lg-12">
                <h1 class="page-header">Contact Us
                    <small>Have a chat with us!</small>
                </h1>
            </div>
        </div>

        <!-- Contact Us Form -->
        <form id="ContactForm" method="post" action="../">
            {% csrf_token %}
            <div class="form-group">
                <label for="name">Name</label>
                <input type="text" class="form-control" id="name" placeholder="Enter name" name="name" value="" size="50" required>
            </div>

            <div class="form-group">
                <label for="email">Email</label>
                <input type="email" class="form-control" id="email" placeholder="Enter email" name="email" value="" size="50" required>
            </div>

            <div class="form-group">
                <label for="message">Message</label>
                <input type="text" class="form-control" id="message" placeholder="Enter Message" name="message" value="" size="150" required>
            </div>
            <button type="submit" class="btn btn-default">Submit</button>
        </form>

        <div>
            <h3><font face="Berlin Sans FB">For Further Enquiries</font></h3>
            <strong>Ring us:</strong>01413397641 </br>
            <strong>Send us an email:</strong>help@workoutweb.com </br>
            <img src="{% static 'images/findus.jpg' %}" alt="Our HQ" />
        </div>

        <div>
            <strong>Or even visit us!</strong>
            <strong>Need more info?</strong><a href="{% url 'workoutweb:faq' %}">FAQ</a></br>
        </div>
    </div>

{%  endblock %}

templates/workoutweb/faq.html
{% extends 'workoutweb/base.html' %}


{% block title_block %}
    Frequently Asked Questions
{% endblock %}

{%  block body_block %}

    <div class="container">
        <!-- Introduction Row -->
        <div class="row">
            <div class="col-lg-12">
                <h1 class="page-header">Frequently Asked Questions
                    <small>You've got questions, we have answers !</small>
                </h1>
            </div>
        </div>
    </div>

        <!-- QUESTIONS -->
        <section class="faq-section">
            <input type="checkbox" id="q1">
            <label for="q1">What should I use WorkoutWeb for?</label>
            <p> You can use WorkoutWeb for all things fitness and health!</p>
            <p> As long as you respect all other users and their
                opinions, you will be able to enjoy your time as a member! Feel free to to comment on posts, share your opinions,
                and get the latest tips and tricks.
            </p>
        </section>

        <section class="faq-section">
            <input type="checkbox" id="q2">
            <label for="q2">Who are we?</label>
            <p> We are the keen computer scientist behind the idea of WorkoutWeb!
            </p>
            <p> If you want to know more about us, check out the About Us Section.
            </p>
        </section>

        <section class="faq-section">
            <input type="checkbox" id="q3">
            <label for="q3">How do I create a WorkoutWeb account?</label>
            <p> If you don't have a Facebook account, you can create one in a few steps:
            </p>
            <p> > Go to www.workoutweb.com OR localHost:8000 :D<br>
                > Click on the "sign-up" button in the top right corner of any page.<br>
                > Fill in the required fields<br>
                > Click 'Register'<br>
                <br>
                If you already have a WorkoutWeb account, you can log into your
                account by entering your username and password and clicking Log In.
            </p>
        </section>

        <section class="faq-section">
            <input type="checkbox" id="q4">
            <label for="q4">I've forgotten my password!</label>
            <p> If you've forgotten your password, please proceed your profile page
            </p>
            <p> Passwords can be changed accessing the link on the account settings page
                along with additional information such as weight, height and bio
            </p>
        </section>

        <section class="faq-section">
            <input type="checkbox" id="q5">
            <label for="q5">What names are allowed on WorkoutWeb?</label>
            <p> WorkoutWeb is a community where everyone uses any name they'd prefer to be called by.
            </p>
            <p> Your name can't include:<br>
                > Symbols, numbers, unusual capitalization, repeating characters or punctuation<br>
                > Characters from multiple languages<br>
                > Titles of any kind (ex: professional, religious)<br>
                > Words or phrases in place of a name<br>
                > Offensive or suggestive words of any kind<br>
            </p>
        </section>

        <section class="faq-section">
            <input type="checkbox" id="q6">
            <label for="q6">Your Home Page</label>
            <p> We have designed WorkoutWeb such that it always shows the top 5 posts on each topic.
            </p>
            <p> This way we can make sure to keep our members up to date with the best of the best
                posts out there. We are still in the developing stage so please send us any suggestions
                through the 'Contact Us' page above. :)
            </p>
        </section>

        <section class="faq-section">
            <input type="checkbox" id="q7">
            <label for="q7">I can't access all the information on the forum.</label>
            <p> You can only see everything on the website as a signed-up member.
            </p>
            <p> If you don't have an account yet, you can create one
                by clicking on the "sign-up" button in the top right corner.
            </p>
        </section>

        <section class="faq-section">
            <input type="checkbox" id="q8">
            <label for="q8">Who can be a member?</label>
            <p> Anyone can be a member of WorkoutWeb.
            </p>
            <p> As long as you respect other users and don't use foul or discriminative language
                we are happy for anyone to make use of WorkoutWeb!
            </p>
        </section>

        <section class="faq-section">
            <input type="checkbox" id="q9">
            <label for="q9">Contacting Us</label>
            <p> WorkoutWeb is committed to creating a great experience for all people.
            </p>
            <p> if you encounter an issue and would like to complain we recommend that you
                immediately inform a representative of WorkoutWeb through the Contact us.
                If they are unable to resolve your issue to your satisfaction you must then
                contact our support team.
            </p>
        </section>

        <section class="faq-section">
            <input type="checkbox" id="q10">
            <label for="q10">How do I change my user details?</label>
            <p> You can change your account information using the Account Settings.
            </p>
            <p> For basic profile details (including your email address and password) click
                on Account settings when you are logged in .This page allows you to set
                a number of required and optional details, some of
                which will be displayed on your public profile. With the exception of
                your email address, do not enter information that you do not wish to be
                publicly viewable.
            </p>
        </section>

        <section class="faq-section">
            <input type="checkbox" id="q11">
            <label for="q9">Accessibility</label>
            <p> WorkoutWeb is committed to creating a great experience for all people.
            </p>
            <p> Learn about the built-in features and technologies that help
                people with disabilities, like vision loss and deafness, to get the most
                out of WorkoutWeb.
            </p>
        </section>

        <section class="faq-section">
            <input type="checkbox" id="q12">
            <label for="q9">I found a bug! Now what?</label>
            <p> The most important things when reporting a bug are to be as specific as possible
            </p>
            <p> If the bug is not known about, please give us enough information that we can
                reproduce the bug ourselves on the correct operating system. Otherwise it's
                unlikely that we'll be able to fix it.
            </p>
        </section>


{% endblock %}

templates/workoutweb/index.html
{% extends 'workoutweb/base.html' %}
{% load staticfiles %}


{% block title_block %}
    Index Page
{% endblock %}


{% block body_block %}

    <!-- Page Content -->
    <div class="container">

        <!-- Heading Row -->
        <div class="row">
            <div class="col-md-8">
                <div class="container">
                      <div class="jumbotron" style="text-align:center">
                        <h1><font face="Berlin Sans FB">Welcome to Workout Web </font></h1>
                        <p><font face="Cambria">Here at Workout Web the user is the priority. We offer an open and professional environment for users
                        to share and post their tips and opinions on everything workout and fitness.</font></p>
                      </div>
                </div>
            </div>
        </div>
        <hr>
    </div>

    <div>

        <!-- Tables -->
        {% if categories %}
        <ul>
            {%  for  key,value in categories.items %}
                <div class="tab">
                    <h3><font face="Berlin Sans FB"><a href="{% url 'workoutweb:show_category' key.slug %}">{{ key.name }}</a></font></h3>
                </div>
            <table>
                <thead>
                    <tr>
                        <th><font face="Cambria">Title</font></th>
                        <th><font face="Cambria">Post</font></th>
                        <th><font face="Cambria">Likes</font></th>
                        <th><font face="Cambria">Views</font></th>
                    </tr>
                </thead>

                {% for post in value %}
                <tbody>
                <tr>
                    <td><strong>{{post.title}}</strong></td>
                    <td>{{post.content}}</td>
                    <td>{{post.likes}}</td>
                    <td>{{post.views}}</td>
                </tr>
                    {% endfor %}
                </tbody>
            </table>
            {% endfor %}
        </ul>
    {% else %}
        <strong>There are no categories present.</strong>
        {% endif %}
    </div>

{% endblock %}

templates/workoutweb/nearest_gym.html
{% extends 'workoutweb/base.html' %}

{% block title_block %}
    Frequently Asked Questions
{% endblock %}

{%  block body_block %}

 <!-- Introduction Row -->
<div class="container">
    <div>
        <h1 class="page-header">Find Nearest Gym
            <small>Your local gyms!</small>
        </h1>
    </div>
</div>

<center>

    <iframe src="https://www.google.com/maps/embed?pb=!1m12!1m8!1m3!1d17906.846362982084!2d-4.288311408984377!3d55.873842611950565!3m2!1i1024!2i768!4f13.1!2m1!1sgyms!5e0!3m2!1sen!2suk!4v1489679199242"
            width="1600" height="650" frameborder="0" style="border:0" allowfullscreen></iframe>
</center>
{% endblock %}